Vagrant.configure("2") do |config| # version 2
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "ubuntu-docker"
  
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "ubuntu-docker"
  end
end
