Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "vm1" do |vm1|
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
    end
    vm1.vm.network "forwarded_port", guest: 80, host: 8080

    vm1.vm.provision "shell", privileged: true, inline: <<-SHELL
      apt update
      apt -y install nginx
      systemctl enable nginx
      systemctl start nginx
    SHELL

    vm1.vm.network "private_network", ip: "172.20.0.78"
  end 

  config.vm.define "vm2" do |vm2|
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "vm2"
    end
    vm2.vm.disk :disk, size: "60GB", primary: true
    vm2.vm.network "public_network"

    vm2.vm.provision "shell", privileged: true, path: "https://get.docker.com"
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.provider "virtualbox" do |vb|
      vb.name = "vm3"
    end
    vm3.vm.network "private_network", ip: "172.20.0.87"

    vm3.vm.provision "shell", privileged: true, inline: <<-SHELL
      apt update
      apt -y install zsh
      useradd -m -s /bin/zsh -G sudo -g adam adam
      echo "adam ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/adam 
    SHELL
  end
end
