Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "lab4"

  config.vm.provision "shell", privileged: true, path: "https://get.docker.com"
  config.vm.network "forwarded_port", guest: 10086, host: 10086
  
  config.vm.provision "shell", inline: <<-SHELL
    cp /vagrant/Dockerfile .
    cp /vagrant/docker-compose.yml .
    mkdir wireguard
    cp /vagrant/wg.conf ./wireguard/wg.conf
    sudo docker compose up --build -d
  SHELL
end
