services:
  dns:
    container_name: dns
    hostname: dns
    image: adguard/adguardhome:latest
    
    ports:
      - 53:53/udp
      - 53:53/tcp
    networks:
      - lab5_network

    volumes:
      - volume_dns_work:/opt/adguardhome/work
      - volume_dns_home:/opt/adguardhome/conf
        #     - ./AdGuardHome.yaml:/opt/adguardhome/conf/AdGuardHome.yaml

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

    restart: unless-stopped
 
  nginx:
    container_name: web
    hostname: web
    image: nginx:latest

    ports:
      - 80:80
      - 443:443
    networks:
      - lab5_network

    volumes:
      - ./nginx/conf/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/ssl
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

    restart: unless-stopped

    depends_on:
      - dns
      - registry


  registry:
    container_name: registry
    hostname: registry
    image: registry:2

    networks:
      - lab5_network

    volumes:
      - ./auth:/auth

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

    restart: unless-stopped

    depends_on:
      - dns

    environment:
      - REGISTRY_AUTH=htpasswd
      - "REGISTRY_AUTH_HTPASSWD_REALM=Regstry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd

networks:
  lab5_network:
    driver: bridge

volumes:
  volume_dns_work:
  volume_dns_home:
