Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "lab5"
  
  config.vm.provision "shell", privileged: true, path: "https://get.docker.com"
  config.vm.provision "file", source: "./nginx", destination: "nginx", run: "always"
  config.vm.provision "file", source: "./docker-compose.yml", destination: "docker-compose.yml", run: "always"
  config.vm.network "public_network", ip: "192.168.1.200"

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    sudo sed -i 's/#DNS=/DNS=127.0.0.1/' /etc/systemd/resolved.conf
    sudo sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf 
    sudo systemctl restart systemd-resolved
    sudo docker compose up -d
    sudo docker build /vagrant/ -t wg-ubuntu
    sudo docker tag wg-ubuntu registry.student:443/wg-ubuntu:latest
  SHELL
end
