Vagrant.configure("2") do |config|
  config.vm.define "lab2"
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.disk :disk, size: "60GB", primary: true
  config.vm.disk :disk, size: "10GB", name: "second"

  config.vm.hostname = "vm1.local"

  config.vm.network "forwarded_port", guest: 22, host: 3333
  config.vm.network "private_network", ip: "172.20.0.2"
  config.vm.network "public_network"

  config.vm.provision "shell", privileged: true, path: "https://get.docker.com"
end
