Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/jammy64"

  config.vm.provision "shell", privileged: true, path: "https://get.docker.com"

  config.vm.define "manger1" do |m1|
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "m1"
    end
    m1.vm.network "private_network", ip: "192.168.56.10"
    m1.vm.hostname = "manger1"

  end


  config.vm.define "worker1" do |w1|
    w1.vm.provider "virtualbox" do |vb|
      vb.name = "w1"
    end
    w1.vm.network "private_network", ip: "192.168.56.20"
    w1.vm.hostname = "worker1"
  

  end

  config.vm.define "worker2" do |w2|
    w2.vm.provider "virtualbox" do |vb|
      vb.name = "w2"
    end
    w2.vm.network "private_network", ip: "192.168.56.30"
    w2.vm.hostname = "worker2"
  end
end
