services:
  web:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
        #volumes:
        #      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

    networks:
      - web_network

    deploy:
      mode: global

  nginx:
    image: nginx:latest
    networks:
      - web_network
    deploy:
      placement:
        constraints:
          - node.hostname == manger1
    ports:
      - 1103:8080
    volumes:
      - /vagrant/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

networks:
  web_network:
    driver: overlay
