services:
  web:
    image: python:buster
    command: python -m http.server 8010
    ports:
      - 8010:8010
    networks:
      - web_network
    deploy:
      mode: global
    restart: unless-stopped

  nginx:
    image: nginx:latest
    networks:
      - web_network
    deploy:
      placement:
        constraints:
          - node.hostname == manger1
    ports:
      - 1103:8080
    volumes:
      - /vagrant/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: unless-stopped

networks:
  web_network:
    driver: overlay
