Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/jammy64"

  config.vm.provision "shell", privileged: true, path: "https://get.docker.com"

  config.vm.define "manger1" do |m1|
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "m11"
    end
    m1.vm.network "forwarded_port", guest: 1101, host: 1101
    m1.vm.network "forwarded_port", guest: 1102, host: 1102
    m1.vm.network "forwarded_port", guest: 1103, host: 1103
    m1.vm.network "private_network", ip: "3.22.111.10"
    m1.vm.hostname = "manger1"
    m1.vm.provision "shell", privileged: true, inline: "docker swarm init --advertise-addr 3.22.111.10"
    m1.vm.provision "shell", privileged: true, inline: "docker swarm join-token worker -q > /vagrant/swarm_token" 

    m1.vm.provision "shell", privileged: true, inline: <<-SHELL
      docker stack deploy -c /vagrant/visualizer.yml visualizer
      docker stack deploy -c /vagrant/portainer.yml portainer
      docker stack deploy -c /vagrant/easy.yml easy
    SHELL
  end
  
  (1..2).each do |i|
    config.vm.define "worker#{i}" do |w|
      w.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}"
      end
      w.vm.network "private_network", ip: "3.22.111.1#{i}"
      w.vm.hostname = "worker#{i}"
     
      w.vm.provision "shell", privileged: true, inline: <<-SHELL
        docker swarm join --token `cat /vagrant/swarm_token` 3.22.111.10:2377
      SHELL
    end
  end

end
